services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
            - 4433:443
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    mysql:
        image: mysql:8.1
        container_name: mysql
        ports:
            - 3307:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: rootpass123
            MYSQL_DATABASE: ecommerce
           # MYSQL_USER: root
            MYSQL_PASSWORD: db_password
          #  MYSQL_ALLOW_EMPTY_PASSWORD: 1

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8090:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        image: adminer:latest
        ports:
            - 9090:8080
        depends_on:
            - mysql


    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:8.0
        command: redis-server --appendonly yes
        platform: linux/amd64
        restart: always
        volumes:
            - .docker/redis/data:/data
        ports:
            - 6379:6379



